---
title: "PS270 Final Project"
author: "Kate Schimkat"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts

I am interested in exploring data related to... 
- The election
- Healthcare: healthcare inequality
- Public health: Maybe chronic disease & food additives? I've always been interested in exploring topics related to public health and think exploring related data would be really interesting & beneficial to have as a project. 

## Research Question

Do perspectives on media bias relate to party affiliation? In this study, I plan to examine to what extent individual beliefs on the importance of punishing mainstream media bias relate to which political party the individual identifies as. I hypothesize that there is a relationship between political parties and how individuals within them value the importance of addressing media bias, with members of the Republican Party being more likely to view media bias as more extreme. In today's political climate, claims of media bias and partisan news stations are rampant, targeting both political parties and many organizations. However, I believe that with former President Donald Trump's rampant and relentless rants on the dangers of fake news, that Republicans are more likely to see this is a major issue. Additionally, with the events of January 6 of Republicans storming the country capital, I also think it likely for Republicans to follow through with taking action against "false claims," whether these claims are toward election results or general mainstream media, and therefore answer this survey that the mainstream media "should be punished" for its bias. My explanatory variable is how much respondents agree with the claim "the mainstream media is biased and should be punished." Their responses are measured on a scale of 1 to 4, with 1 being they strongly disagree with the statement and 4 being they strongly agree. My outcome variable is party affiliation, with 1 meaning they are a democrat, 2 meaning they are a republican, 3 meaning they are independent, and 4 meaning they identify with another political party. If respondents who more strongly agreed with the mainstream media being biased and having to be punished are more likely to identify as republican, then my hypothesis will be supported by the results. However, if the results don't indicate perspectives on media bias relate to a specific political party, or if they show democrats or independents are more likely to see the mainstream media as biased, then the results will not support my initial hypothesis.  
